name: Build storybook

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: npm install

      - name: Test
        run: npm run chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
